version: "3"
services:
    nginx:
        container_name: nginx
        hostname: nginx
        build: ./nginx
        image: slidelinker-nginx
        env_file:
            - ./.env
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - frontend
            - backend
            - db

    frontend:
        container_name: frontend
        hostname: frontend
        build: ./frontend/src
        image: slidelinker-frontend
        env_file:
            - ./.env
        volumes:
            - ./frontend/src:/frontend
            - /frontend/node_modules # Exclude the node_modules directory
        depends_on:
            - backend
            - db

    backend:
        container_name: backend
        hostname: backend
        build: ./backend/src
        image: slidelinker-backend
        env_file:
            - ./.env
        volumes:
            - ./backend/src:/backend
            - /backend/node_modules # Exclude the node_modules directory
        depends_on:
            - db

    db:
        container_name: database
        hostname: database
        build: ./database
        image: slidelinker-database
        env_file:
            - ./.env
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"
