const fonts = [
    "AR JULIAN",
    "Arial",
    "Arial Black",
    "Arial Narrow",
    "Bahnschrift",
    "Bahnschrift Condensed",
    "Bahnschrift Light",
    "Bahnschrift SemiBold",
    "Bahnschrift SemiCondensed",
    "Bebas",
    "Bernard MT Condensed",
    "Blackletter686 BT",
    "Brandish",
    "Broadway BT",
    "Caladea",
    "Calibri",
    "Calibri Light",
    "Calligraph421 BT",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Candara Light",
    "Carlito",
    "Cataneo BT",
    "Chaparral Pro Light",
    "Chivo",
    "ChunkFive",
    "Comfortaa",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Corbel",
    "Corbel Light",
    "Courier New",
    "Courier Std",
    "Dataface",
    "David CLM",
    "David Libre",
    "DejaVu Math TeX Gyre",
    "DejaVu Sans",
    "DejaVu Sans Condensed",
    "DejaVu Sans Light",
    "DejaVu Sans Mono",
    "DejaVu Serif",
    "DejaVu Serif Condensed",
    "Didact Gothic",
    "DilemHandwritten",
    "Directive Four",
    "Directive Four Condensed",
    "Earthbound",
    "Ebrima",
    "Ethnocentric",
    "Fanwood",
    "Fanwood Text",
    "Fira Sans ExtraBold",
    "Fira Sans Light",
    "Fira Sans SemiBold",
    "Frank Ruehl CLM",
    "Frank Ruhl Hofshi",
    "Franklin Gothic Medium",
    "FreeUniversal",
    "Gabriola",
    "Gadugi",
    "Gauge",
    "Gauge Heavy",
    "Gen",
    "Gen Light",
    "Gentium Basic",
    "Gentium Book Basic",
    "Geometos",
    "Georgia",
    "Good Times",
    "GranaPadano",
    "Hans Kendrick",
    "Horizon BT",
    "Impact",
    "Ink Free",
    "Javanese Text",
    "Junction",
    "Jura",
    "Klaudia",
    "Knewave Outline",
    "Lato",
    "Lato Black",
    "Lato Light",
    "Lato Semibold",
    "Lavoir",
    "League Gothic Condensed",
    "League Script Thin",
    "Leelawadee UI",
    "Leo Arrow",
    "Liberation Mono",
    "Liberation Sans",
    "Liberation Sans Narrow",
    "Liberation Serif",
    "Linden Hill",
    "Linearmente",
    "Linux Biolinum G",
    "Linux Libertine Display G",
    "Linux Libertine G",
    "Logisoso",
    "Lucida Console",
    "Lucida Sans Unicode",
    "Malgun Gothic",
    "Medieval Sharp",
    "Mexcellent",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei UI Light",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft YaHei Light",
    "Microsoft YaHei UI",
    "Microsoft YaHei UI Light",
    "Microsoft Yi Baiti",
    "MingLiU-ExtB",
    "MingLiU_HKSCS-ExtB",
    "Minion Pro",
]

export default fonts
