/*
 * Here the action types for projects and projects' slides are defined
 */

/* Project action types */

export const REQUEST_GET_PROJECTS = "REQUEST_GET_PROJECTS"
export const RECEIVE_GET_PROJECTS = "RECEIVE_GET_PROJECTS"
export const ERROR_GET_PROJECTS = "ERROR_GET_PROJECTS"

export const REQUEST_ADD_PROJECT = "REQUEST_ADD_PROJECT"
export const RECEIVE_ADD_PROJECT = "RECEIVE_ADD_PROJECT"
export const ERROR_ADD_PROJECT = "ERROR_ADD_PROJECT"

export const REQUEST_GET_PROJECT = "REQUEST_GET_PROJECT"
export const RECEIVE_GET_PROJECT = "RECEIVE_GET_PROJECT"
export const ERROR_GET_PROJECT = "ERROR_GET_PROJECT"

export const REQUEST_UPDATE_PROJECT = "REQUEST_UPDATE_PROJECT"
export const RECEIVE_UPDATE_PROJECT = "RECEIVE_UPDATE_PROJECT"
export const ERROR_UPDATE_PROJECT = "ERROR_UPDATE_PROJECT"

export const REQUEST_DELETE_PROJECT = "REQUEST_DELETE_PROJECT"
export const RECEIVE_DELETE_PROJECT = "RECEIVE_DELETE_PROJECT"
export const ERROR_DELETE_PROJECT = "ERROR_DELETE_PROJECT"

/* Slide action types */

export const REQUEST_GET_SLIDES = "REQUEST_GET_SLIDES"
export const RECEIVE_GET_SLIDES = "RECEIVE_GET_SLIDES"
export const ERROR_GET_SLIDES = "ERROR_GET_SLIDES"

export const REQUEST_ADD_SLIDE = "REQUEST_ADD_SLIDE"
export const RECEIVE_ADD_SLIDE = "RECEIVE_ADD_SLIDE"
export const ERROR_ADD_SLIDE = "ERROR_ADD_SLIDE"

export const REQUEST_GET_SLIDE = "REQUEST_GET_SLIDE"
export const RECEIVE_GET_SLIDE = "RECEIVE_GET_SLIDE"
export const ERROR_GET_SLIDE = "ERROR_GET_SLIDE"

export const REQUEST_UPDATE_SLIDE = "REQUEST_UPDATE_SLIDE"
export const RECEIVE_UPDATE_SLIDE = "RECEIVE_UPDATE_SLIDE"
export const ERROR_UPDATE_SLIDE = "ERROR_UPDATE_SLIDE"

export const REQUEST_DELETE_SLIDE = "REQUEST_DELETE_SLIDE"
export const RECEIVE_DELETE_SLIDE = "RECEIVE_DELETE_SLIDE"
export const ERROR_DELETE_SLIDE = "ERROR_DELETE_SLIDE"
