/*
 * Here the action types for projects and projects' slides are defined
 */

export const REQUEST_TOKEN = "REQUEST_TOKEN"
export const RECEIVE_TOKEN = "RECEIVE_TOKEN"
export const ERROR_TOKEN = "ERROR_TOKEN"

export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const RECEIVE_LOGIN = "RECEIVE_LOGIN"
export const ERROR_LOGIN = "ERROR_LOGIN"

export const REQUEST_REGISTER = "REQUEST_REGISTER"
export const RECEIVE_REGISTER = "RECEIVE_REGISTER"
export const ERROR_REGISTER = "ERROR_REGISTER"

export const REQUEST_UNREGISTER = "REQUEST_UNREGISTER"
export const RECEIVE_UNREGISTER = "RECEIVE_UNREGISTER"
export const ERROR_UNREGISTER = "ERROR_UNREGISTER"

export const REQUEST_GET_USERS = "REQUEST_GET_USERS"
export const RECEIVE_GET_USERS = "RECEIVE_GET_USERS"
export const ERROR_GET_USERS = "ERROR_GET_USERS"

export const REQUEST_GET_USER = "REQUEST_GET_USER"
export const RECEIVE_GET_USER = "RECEIVE_GET_USER"
export const ERROR_GET_USER = "ERROR_GET_USER"

export const REQUEST_UPDATE_USER = "REQUEST_UPDATE_USER"
export const RECEIVE_UPDATE_USER = "RECEIVE_UPDATE_USER"
export const ERROR_UPDATE_USER = "ERROR_UPDATE_USER"

export const REQUEST_DELETE_USER = "REQUEST_DELETE_USER"
export const RECEIVE_DELETE_USER = "RECEIVE_DELETE_USER"
export const ERROR_DELETE_USER = "ERROR_DELETE_USER"

export const LOGOUT = "LOGOUT"
